apiVersion: v1
kind: Namespace
metadata:
  name: authc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: authc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --upstream=file:///dev/null
        - --https-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: 788e9c977b94ac2b3b7d
        - name: OAUTH2_PROXY_CLIENT_SECRET          
          value: eb37dd51dcf2ac48567fc0e3b359ca8743d0ac9b
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: LJQqVzZY28O4hXj1DVc0lA==
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: authc
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: authc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: minikube.local
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
            service:
              name: oauth2-proxy
              port:
                number: 4180
---
apiVersion: v1
kind: Secret
metadata:
  name: minikube
  namespace: authc
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd01QQ1N3WWVKQXRHenhhMGZNQjB2OWhqb0E1bUkvUUx2RnlGalU0TzNsZFdEd2JhCkgvaUJ2SWpFQjM1NWZVNDM5V1E1T3JRWjNqRmNMaVpDWHkvNGwyWWlOTnFjdTV2Q1V1SVQ1UWdlamk5ZXp2aXAKbDE2bWxkWnJleUlNUFV3WWxzMVVJQ0ZONGpoN21VU2ZuaXAzSzByM0M5SHI4Y3NmVzJYUlErV2kxMWVxS2ZVcgpzTzRuc0crNFpwZjlJSWFDeHp3QlU0VzBNNVRlL2hmTFB5NUIrejJkMk00NkM3Q1dKcWdmc2czUXRCMWN5S2FICm5GWlJJTk5CbzN5WTNZaitkdzcyMko4TFRlUFFGbkVoZ1FTd2puSmNhMFJQNnJhMzJlMmhYZHVBWlFnYlVjSDEKZUR3UEJJQzFITk5QYVRoS0d3YWdYTklUYWFuU1kvYlNWZE1YMVFJREFRQUJBb0lCQUdPY1JTaVRycnVkZ0NlLwphZUVWYXI5QVNLc0xCY2tLY1k0U21ZamRqMTFoOER5dm84UGxuTlVhTDRKWDN0dmJzWnNEQVhmT1haZXVGaDVhCjh1MVJVcnFac285eGNKQ1orcDd0NkszdnRpcHZYQ1RENW84c0FCVnB5ZnpGS1dIN2tyRkt4WEFkQmF3aTErdnAKeERudFk4dGhYNndoL0RUa2EvM0U3WkNTZDhXaXg4MXhSeWo1ZWRoVU1NVWtBSmZvS0ZIdDZaMEUrcmFDUk16bwo4ZWtOZ01ySUlGeGN6V2doTHV3b0xhU1MzZVJkMVFaLzBuQ2FFb2d1dC9yUHRQdWlGa0x4THdDbWNmUUQwcDdjCkxVQlFjTzFQR3lGUjNSUThFeW1jMWF0elJYRldMRE8zaVl2d1huL20rMHV5a1luOVlMdzFERlVJcWVWTXd3c00KOEFjRUx2a0NnWUVBNHhmOEtyS3FQVm9PQ3VjQmQxamtrNEQ0ZTIyUFFLOWY4QVRLc1luYVEycTlkeFA5U3hqVgozVUZmYitCalg4RGZZTjcrYmZ4TzBDTW8zaGdmeTQxS0N2TlZVOU0rYXhPTnVnVDlwRTFSUlFMdDZRWlM0OTVTCllEL3JOaitRMWNwSTNpKzBnTXBzQnJpSGo2L1I0SERmRkNnamJpQzFGa0lCOUR4dEkvMk1QSmNDZ1lFQTJVMGoKVU5UbGdvVlM3ZEV3K1dmMUpRanROeXR4UXBUKzgyekRLMExENXVySDRUQ3hPMW1jR0FhUS9BcFRZc28rT3dPegpBaXhhd0p0eWExVjduV2lBdTNLZGhGalYwYmpaUzBlaEpWUit1UnEwSGFPMUNUKzEwZUd6Y2Y2N2dPTmc5c0gyClFTeXIvSitSRzN6bFpRU2FRb0FNdVBCd0pmSFVTSGZ3Q2lUbklITUNnWUVBMU5GQWJ4ODZiUDU5RkhpQ0pqOTMKRGtpYUZNbUtxenJ1OUhiNUlVSW4rbkFJbUpSeUZqTnpFTU5YMWZkNkNWMHR1WkdnN0orN21GQ3ExdC9TeENabgpraldSN0ZtV01EQ0Y3Q01MTkRPRkN1Q0E1cFVYanhabEtuQWNWSjFqZFFiNkhNYW1LT0FLTm80dDlGajNuWmNKClo5RnB5cVg2THA2elNCaHN5NEtzTG9jQ2dZQlp5OENPUkl2YkZkRWhLVkw5blhIMkxld280akRaZk15bU53bW4KdE4xVGJTM1A1dGsyVjE5anBrTC9oQnpWTkJIblBTNFo5YzVDelhuSTFQaFNJYjhndHNwVXlJa0RNMG5JQy8rUgpkNHN1WHRTVGN2VDZyM01wR2dXWFU5YVQrbUkxVmcyMi9Rak5TZnNpeXNmWXFNQStQc0FESklpVGhZMWRyUUpxCmpybGI5UUtCZ0V5MGxuMXFWa3crMDF5TVZpV3ZFRGxubUNPU1A3dThYaUNqRCswanU0U3FqZGl4dVZQQm9BZVQKaEsvR1ZSeW9PeDA1Y3d2S0FKaDljajRIYUZhYmhGRXNUL0tFTHZ3S1ZwN2hzSjY2cEFwenhlaVZ5V2czWFl0QgpaZEF1MHh0ZkRpYzBrN0p1WElwMG1RaCtEOW1yR1A0dmJLRXRWUGxSWko1WmJFdUhlZGkvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQWRXZ0F3SUJBZ0lKQVBqUVBZYVF1Zm1STUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOekV4TVRrME1UVXdXaGNOTXpFd016SXdNVGswTVRVdwpXakFUTVJFd0R3WURWUVFEREFodGFXNXBhM1ZpWlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1ERHdrc0dIaVFMUnM4V3RIekFkTC9ZWTZBT1ppUDBDN3hjaFkxT0R0NVhWZzhHMmgvNGdieUkKeEFkK2VYMU9OL1ZrT1RxMEdkNHhYQzRtUWw4ditKZG1JalRhbkx1YndsTGlFK1VJSG80dlhzNzRxWmRlcHBYVwphM3NpREQxTUdKYk5WQ0FoVGVJNGU1bEVuNTRxZHl0Szl3dlI2L0hMSDF0bDBVUGxvdGRYcWluMUs3RHVKN0J2CnVHYVgvU0NHZ3NjOEFWT0Z0RE9VM3Y0WHl6OHVRZnM5bmRqT09ndXdsaWFvSDdJTjBMUWRYTWltaDV4V1VTRFQKUWFOOG1OMkkvbmNPOXRpZkMwM2owQlp4SVlFRXNJNXlYR3RFVCtxMnQ5bnRvVjNiZ0dVSUcxSEI5WGc4RHdTQQp0UnpUVDJrNFNoc0dvRnpTRTJtcDBtUDIwbFhURjlVQ0F3RUFBYU0vTUQwd0NRWURWUjBUQkFJd0FEQUxCZ05WCkhROEVCQU1DQmVBd0l3WURWUjBSQkJ3d0dvSUliV2x1YVd0MVltV0NEbTFwYm1scmRXSmxMbXh2WTJGc01BMEcKQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUNFT3cyUDRUekhDVVF6UnkyekcrV3k0aEtGd1cyY2lONmt4NFJ4Q0hhSQpDdGViRStjajBiRnl2Z085Wk1XMzFyMGFFaUdpLzBZWjZ4T2tqUklyM0ZiazJzNFhwY3BIWVRGbE85NnAzS0QrCmVXckZiWmZ3NGRYT3dKQm9XN1VEaWRpUmNNaEJUb0ljVTdXRGMzQUlEYUk1cm1vWnZ3WUY5eVJqOUFQZWpnREwKZTNCOHVtMzdVYnY2QWRvN0lVT0tDandNYjZJTUsyS0RVVkp4Wm9iY3FKb1NUMzI3Qzlxb29Ycll0WklzczNRQwpNTkZrNmF3UGNOS0gvWnI4cmZ5UDdpcmN3RkZvSFN4M2ZrZko5WmNWd2M4eTEwa2VqU3I2ZmxpRlNjY1ZlRTZxCllXemRLSUM1UXhra01qT1hVYzYrSTM1ZDg0NHl2TzJQaFBOUDErL2xYd1lCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: ca
  namespace: authc
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lKQU5HVWFRR0d2TVNlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOak13TVRnMU5EQTJXaGNOTXpFd016QTVNVGcxTkRBMgpXakFZTVJZd0ZBWURWUVFERXcxdVozQXRjSEpwYldWeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFzaDR5TStkNmdCR0VUelhpcGswdEJTaGNZWUhNbVRLVUwrZm8rei9rZ3RrMlNYMlYKcFVXK0tVVUxITURLVUEralU1RWI2VHBSNjFBMmdYNDlRaWxIZ2VYMzdLU2E5QVVQU2srbUgzM3FscXZlQ2gvSwoxREt5L3hLZTdONmxoeDRwbVhRV3h2WGZOdWg1eGM0NVpNYW1BM010UzE5OXZGMk1DaWFNSmxMOTJNMmRNSVFMCi9hUTluMjJRYXRKcUNyYlJNZTJlSGQ5aGFnTXh4NmtvbGpCaU5ZUXpXOTQ4bytLa0xNelE2UWE5MElrcnhXb2oKZ3JEaXlidmFqT2VndWlOd3E0eTFCZ2FWSEVTVGE3eUVJYkhLU1RWck1COXFUc0Nva0RzR1p6VXlUU1JnZU45NgpLM2tkRzMrVUkwOWFraDkxVVZ6ckpzVjlXMUxvYU1vUkNmQXI0UUlEQVFBQm8za3dkekFkQmdOVkhRNEVGZ1FVCjVGcDBSL1ArM0QvZWE1Ym9HRU85OVE1VE9YY3dTQVlEVlIwakJFRXdQNEFVNUZwMFIvUCszRC9lYTVib0dFTzkKOVE1VE9YZWhIS1FhTUJneEZqQVVCZ05WQkFNVERXNW5jQzF3Y21sdFpYSXRZMkdDQ1FEUmxHa0JocnpFbmpBTQpCZ05WSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZE81aEVSRWViWjNKYjk0QzJkT2pxCkNoVmtycUl4OTgvYmFSOHppZTJXUmUzRU1YV2I3ei9rOUVGanhsRWxXQkhOL1FpdFZUZzhNeElNd0RFVGZ1TjkKcVBaRE85OE9GRXZZZWxwaTdlM0x3NVlQd2hBT1hBa2laUHFjQ0tZRlRvbFFod3kvQnpvRVpCbmdXK052VkNpWgp6My9XYmMvRmlwUmNwdGVFaUZEL2d3bUFoaFJnYlpjM0NaRHRhUmVBdWRqUjAwY3F2amlLU0d2N0dCMU4zT0xsClpvZEpTd3NBT2lDVGNBMHMwQ0FlNndHaWVOOFhBRnhiYlZhSWpkblRtNUFmWkdsZ0E2cVBjQTU0R1loVE5FTFoKZzlDODdYK2t0SDdLeEFSYndQV0RjcmJnMEI0bGFDYjE0RlRLWnYzVUQ5K2Nqb3p3QXREWXVTQUtKRWdxYnNLYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
type: Opaque
---
apiVersion: v1     
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: authc
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM3pGN0trNWdPZHd0cXNqWS9vU0tRWEdSYXdIRFBmMEVkWEpXUXhKd2VtZloxVmZPCmZ4NXoxdUV3M09TN0NSQnlNSkNNSS9uSXlvRnNzR1h4S0d5YzFsbllJc3hsem1peWx4bFVhWjNFbHpad3plMU0KZzRNQTRycWFyWXhibHFEL3VzcElmdlJzb2t4dyt4TG1oREJMa0ZqdC9SMFlzRHJoRklPS3NBZ3dpbTd1STRregpya2E0b2N3T1NLalc2Q1gweVExWGljUEwvcWNuOXlGd2lMdWQ2eHlMdEpMWG51SmYrRCs3ekwybnZnR2dla0ZVCjRWMjE1MlMwV0F1UEdyUXUxUmM2UEhZVnRwbzhZcGZmY2NCeUtxek9yTjRONTlpRVphNUw0WkQxL2VJSTlaTFYKRWFGb0ZEemtkZk9CbUJjZGdTNnhWZG5salNOTDgwNXJkbGJFMFFJREFRQUJBb0lCQUFiZWZmenFWcG5SUmZLSQpwZTBIWlQzb1llSmFOb2tVM1d0RDdwVzMzcEJWMitWdUEyUDBLdnFGQ2J6eXFUTDVONXA1Q0djZkMrZjNuY0c4CkVYVCtDc0dxR0RYUjlwd29xcjV0d0NSVC83WHJyZ01ZZDQ5Z204bGVsdDRhZ01NZEIySFhVZTNlVmUyVXpyRmIKZm82NDhjcHFna0NWQWFxQzFXU05POXA1RmcxY2wrNG5Ia1Q3YkN2TWVoVW9DbnhFWS84Vi9zTVJIU3pJdHl1bQpwNXVJUTBGaTUvMU5ORnFlaHlNWTFyZjZUNDJQS2I3MFBRaTJIOGZtMjhLeEdNTFJuYll5Q21EODBaam0zbUVzCktCVkJZVmd0N0F5QjA2OS92MXdPODZoaStYbXNXaGw2SjBVejBKOGVjUzNKZVlCVTBFSzVTVmRmR0tZKzdFdHkKd2xrNzdPVUNnWUVBOURla3ZmMHROZHZKU0xsQkFMY3ZEak5KMGhzV0I5elBENTFuT0tEK3NrZUVGTVBBcHVrNQpIT2JvaEVtRnduMmxIb2FyRTZzckU1d2tqODdmZnRjQWVLSndTOGxoV0lJRzlXUEg4ZWM5blNpdm80VnVRME5pCjErYWpMZGdRak13OW5FeGNHL0RFNksrRDhzdmdnUDUyNTE2OUxFTUEyaHdyRWdxeC93RkZIaGNDZ1lFQTZmWXEKdUhDSkxwaStvVTZvL2lIZ1p2Z0FkbktoQ3hnVnlObndvbjdLWnF1U01xRjRnQzlFUTM4QTd4QloxOUJ6OHdYKwpFK2cvaEhiVWpuSDJzdnoxaERiL3RBL3VOUzVzaDlqTGRBWjBTWE5MdEN5bi9rSUtjWUNuWkxCekdnb3hGUHJyClBMTlJTWlpYTFVuSStJQjBtalVJQ2tIaFNydEYxVmNHampnY3JWY0NnWUE4RCt0T1pwUFY2U1lKNHJYZjdTMS8KZXBHdlFNWWNUT3dIMVJocnp2eVU4QTNGNVpiZDlnSDczN1pUd3BsSkNnbXdCa0xRNVlvRW1xUkxVZitaZkZzNwpVQWY2TzU3Ylc2OUdickhnQnBVYXI4VHluSUJQdnFUeW9HQ0ZoOXdhSktrS1phVkpvZDlyc3E3cTZjVmZORFllCkZTakZWLzAvcHluWW1CVEt1STg5SlFLQmdRRGpuaXRSNWFxUk91bTc1ZHRqNDNGK3ZDazNFNjY2TEdTRlZBTloKRkNHMllaV0t6SzEvaUh6UmJlNXFwMjNCR1h5MUkwOWQ3c1pkQ1g4aVZwMjg1WDIzZEFxeUZBMmNqOTNuREhSawpIU05sa2xaRXBHMk1ZSlBvZVZKaUU0am4vS0pqMXZxbHc0K0NHRklZTFlEb3c1Q3R0b3ByOEV4UGVJTW9XOUowCjZ3SjdZUUtCZ0c2ZlJLQ0xsTlk5UjNMNzk2L1hLTE9hdmJZSFN6bDRmU2daOFAzblNKL2VGLzlBY3NOUVJTREgKd2lRNEY2T3FiSHcrQ1I0YnplT3Fwek1KbEpXcUVBTndwRGVnWVM3UkRBR3NLUW1GM2NFajZxR0hJVDVvNy9JSwpUY1hlMHVjdW53OFNTaW1QekJGYU52SGthU09qNmxzaE1RZjdvWkVwajRVa0xFTnMraDVlCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lKQVBqUVBZYVF1Zm1VTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOekl4TVRNMU9UQXdXaGNOTXpFd016TXdNVE0xT1RBdwpXakFYTVJVd0V3WURWUVFEREF4dllYVjBhREl0Y0hKdmVIa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRGZNWHNxVG1BNTNDMnF5TmoraElwQmNaRnJBY005L1FSMWNsWkRFbkI2WjluVlY4NS8KSG5QVzRURGM1THNKRUhJd2tJd2orY2pLZ1d5d1pmRW9iSnpXV2RnaXpHWE9hTEtYR1ZScG5jU1hObkRON1V5RApnd0RpdXBxdGpGdVdvUCs2eWtoKzlHeWlUSEQ3RXVhRU1FdVFXTzM5SFJpd091RVVnNHF3Q0RDS2J1NGppVE91ClJyaWh6QTVJcU5ib0pmVEpEVmVKdzh2K3B5ZjNJWENJdTUzckhJdTBrdGVlNGwvNFA3dk12YWUrQWFCNlFWVGgKWGJYblpMUllDNDhhdEM3VkZ6bzhkaFcybWp4aWw5OXh3SElxck02czNnM24ySVJscmt2aGtQWDk0Z2oxa3RVUgpvV2dVUE9SMTg0R1lGeDJCTHJGVjJlV05JMHZ6VG10MlZzVFJBZ01CQUFHamNUQnZNQWtHQTFVZEV3UUNNQUF3CkN3WURWUjBQQkFRREFnWGdNRlVHQTFVZEVRUk9NRXlDREc5aGRYUm9NaTF3Y205NGVZSVdiMkYxZEdneUxYQnkKYjNoNUxtRjFkR2hqTG5OMlk0SWtiMkYxZEdneUxYQnliM2g1TG1GMWRHaGpMbk4yWXk1amJIVnpkR1Z5TG14dgpZMkZzTUEwR0NTcUdTSWIzRFFFQkJRVUFBNElCQVFCcFMzL1VTdkJ5OFc4M0tuTnJNNU5XUEtjTk56WTJmZXVQClNhK1QvaWQ1K0JSNFpGaTg1eEJyanEyN2I0NE05MXA3RVVsbnRhemo4aTA3aDdLT2dyOHBPZytBeEg2YmViRWsKYlhJR1VISU15SkZRbm1yNzNQeTk2amZNa1JHUXVOYld1aDdlNjVydEtTZXZTYW81UXhYbzVHSGpsRkZ0aGxBWgpqVzVKMGJaMEQ5aWRDVlR1YTd6S1FkMXljaGFlR2NJbGZ0VVVmc3ppZVdIS1lpMG55TkppSitzd2l5ekJsY2pmClJSS25vVnJvUElKTWtGazhGbDVBRlVRSUE4RlVWVkZMSFdaNnZ4UlJWRDlwRzBkSUszYXQ4LzloRnVVeGdXdUYKV1RuN2VRTjgydEM1MVBmVDJFK0czemROWFpNd01hU29qYWtTRXFVZ1ZKeXI4QjZib1Q2SQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
