apiVersion: v1
kind: Namespace
metadata:
  name: contacts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  replicas: 3
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: api-server
        image: johnbelamaric/contacts-api
        imagePullPolicy: Always
        args: [ "-dsn", "api:mypassword@tcp(mysql.db:3306)/contacts?charset=utf8&parseTime=True" ]
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  type: NodePort
  selector:
    app: contacts
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: contacts
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - minikube.local
    secretName: minikube
  rules:
  - host: minikube.local
    http:
      paths:
        - path: /contacts
          pathType: Prefix
          backend:
            service:
              name: api
              port:
                number: 80
---
apiVersion: v1     
kind: Secret
metadata:
  name: minikube
  namespace: contacts
type: kubernetes.io/tls
data:
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd01QQ1N3WWVKQXRHenhhMGZNQjB2OWhqb0E1bUkvUUx2RnlGalU0TzNsZFdEd2JhCkgvaUJ2SWpFQjM1NWZVNDM5V1E1T3JRWjNqRmNMaVpDWHkvNGwyWWlOTnFjdTV2Q1V1SVQ1UWdlamk5ZXp2aXAKbDE2bWxkWnJleUlNUFV3WWxzMVVJQ0ZONGpoN21VU2ZuaXAzSzByM0M5SHI4Y3NmVzJYUlErV2kxMWVxS2ZVcgpzTzRuc0crNFpwZjlJSWFDeHp3QlU0VzBNNVRlL2hmTFB5NUIrejJkMk00NkM3Q1dKcWdmc2czUXRCMWN5S2FICm5GWlJJTk5CbzN5WTNZaitkdzcyMko4TFRlUFFGbkVoZ1FTd2puSmNhMFJQNnJhMzJlMmhYZHVBWlFnYlVjSDEKZUR3UEJJQzFITk5QYVRoS0d3YWdYTklUYWFuU1kvYlNWZE1YMVFJREFRQUJBb0lCQUdPY1JTaVRycnVkZ0NlLwphZUVWYXI5QVNLc0xCY2tLY1k0U21ZamRqMTFoOER5dm84UGxuTlVhTDRKWDN0dmJzWnNEQVhmT1haZXVGaDVhCjh1MVJVcnFac285eGNKQ1orcDd0NkszdnRpcHZYQ1RENW84c0FCVnB5ZnpGS1dIN2tyRkt4WEFkQmF3aTErdnAKeERudFk4dGhYNndoL0RUa2EvM0U3WkNTZDhXaXg4MXhSeWo1ZWRoVU1NVWtBSmZvS0ZIdDZaMEUrcmFDUk16bwo4ZWtOZ01ySUlGeGN6V2doTHV3b0xhU1MzZVJkMVFaLzBuQ2FFb2d1dC9yUHRQdWlGa0x4THdDbWNmUUQwcDdjCkxVQlFjTzFQR3lGUjNSUThFeW1jMWF0elJYRldMRE8zaVl2d1huL20rMHV5a1luOVlMdzFERlVJcWVWTXd3c00KOEFjRUx2a0NnWUVBNHhmOEtyS3FQVm9PQ3VjQmQxamtrNEQ0ZTIyUFFLOWY4QVRLc1luYVEycTlkeFA5U3hqVgozVUZmYitCalg4RGZZTjcrYmZ4TzBDTW8zaGdmeTQxS0N2TlZVOU0rYXhPTnVnVDlwRTFSUlFMdDZRWlM0OTVTCllEL3JOaitRMWNwSTNpKzBnTXBzQnJpSGo2L1I0SERmRkNnamJpQzFGa0lCOUR4dEkvMk1QSmNDZ1lFQTJVMGoKVU5UbGdvVlM3ZEV3K1dmMUpRanROeXR4UXBUKzgyekRLMExENXVySDRUQ3hPMW1jR0FhUS9BcFRZc28rT3dPegpBaXhhd0p0eWExVjduV2lBdTNLZGhGalYwYmpaUzBlaEpWUit1UnEwSGFPMUNUKzEwZUd6Y2Y2N2dPTmc5c0gyClFTeXIvSitSRzN6bFpRU2FRb0FNdVBCd0pmSFVTSGZ3Q2lUbklITUNnWUVBMU5GQWJ4ODZiUDU5RkhpQ0pqOTMKRGtpYUZNbUtxenJ1OUhiNUlVSW4rbkFJbUpSeUZqTnpFTU5YMWZkNkNWMHR1WkdnN0orN21GQ3ExdC9TeENabgpraldSN0ZtV01EQ0Y3Q01MTkRPRkN1Q0E1cFVYanhabEtuQWNWSjFqZFFiNkhNYW1LT0FLTm80dDlGajNuWmNKClo5RnB5cVg2THA2elNCaHN5NEtzTG9jQ2dZQlp5OENPUkl2YkZkRWhLVkw5blhIMkxld280akRaZk15bU53bW4KdE4xVGJTM1A1dGsyVjE5anBrTC9oQnpWTkJIblBTNFo5YzVDelhuSTFQaFNJYjhndHNwVXlJa0RNMG5JQy8rUgpkNHN1WHRTVGN2VDZyM01wR2dXWFU5YVQrbUkxVmcyMi9Rak5TZnNpeXNmWXFNQStQc0FESklpVGhZMWRyUUpxCmpybGI5UUtCZ0V5MGxuMXFWa3crMDF5TVZpV3ZFRGxubUNPU1A3dThYaUNqRCswanU0U3FqZGl4dVZQQm9BZVQKaEsvR1ZSeW9PeDA1Y3d2S0FKaDljajRIYUZhYmhGRXNUL0tFTHZ3S1ZwN2hzSjY2cEFwenhlaVZ5V2czWFl0QgpaZEF1MHh0ZkRpYzBrN0p1WElwMG1RaCtEOW1yR1A0dmJLRXRWUGxSWko1WmJFdUhlZGkvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQWRXZ0F3SUJBZ0lKQVBqUVBZYVF1Zm1STUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOekV4TVRrME1UVXdXaGNOTXpFd016SXdNVGswTVRVdwpXakFUTVJFd0R3WURWUVFEREFodGFXNXBhM1ZpWlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1ERHdrc0dIaVFMUnM4V3RIekFkTC9ZWTZBT1ppUDBDN3hjaFkxT0R0NVhWZzhHMmgvNGdieUkKeEFkK2VYMU9OL1ZrT1RxMEdkNHhYQzRtUWw4ditKZG1JalRhbkx1YndsTGlFK1VJSG80dlhzNzRxWmRlcHBYVwphM3NpREQxTUdKYk5WQ0FoVGVJNGU1bEVuNTRxZHl0Szl3dlI2L0hMSDF0bDBVUGxvdGRYcWluMUs3RHVKN0J2CnVHYVgvU0NHZ3NjOEFWT0Z0RE9VM3Y0WHl6OHVRZnM5bmRqT09ndXdsaWFvSDdJTjBMUWRYTWltaDV4V1VTRFQKUWFOOG1OMkkvbmNPOXRpZkMwM2owQlp4SVlFRXNJNXlYR3RFVCtxMnQ5bnRvVjNiZ0dVSUcxSEI5WGc4RHdTQQp0UnpUVDJrNFNoc0dvRnpTRTJtcDBtUDIwbFhURjlVQ0F3RUFBYU0vTUQwd0NRWURWUjBUQkFJd0FEQUxCZ05WCkhROEVCQU1DQmVBd0l3WURWUjBSQkJ3d0dvSUliV2x1YVd0MVltV0NEbTFwYm1scmRXSmxMbXh2WTJGc01BMEcKQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUNFT3cyUDRUekhDVVF6UnkyekcrV3k0aEtGd1cyY2lONmt4NFJ4Q0hhSQpDdGViRStjajBiRnl2Z085Wk1XMzFyMGFFaUdpLzBZWjZ4T2tqUklyM0ZiazJzNFhwY3BIWVRGbE85NnAzS0QrCmVXckZiWmZ3NGRYT3dKQm9XN1VEaWRpUmNNaEJUb0ljVTdXRGMzQUlEYUk1cm1vWnZ3WUY5eVJqOUFQZWpnREwKZTNCOHVtMzdVYnY2QWRvN0lVT0tDandNYjZJTUsyS0RVVkp4Wm9iY3FKb1NUMzI3Qzlxb29Ycll0WklzczNRQwpNTkZrNmF3UGNOS0gvWnI4cmZ5UDdpcmN3RkZvSFN4M2ZrZko5WmNWd2M4eTEwa2VqU3I2ZmxpRlNjY1ZlRTZxCllXemRLSUM1UXhra01qT1hVYzYrSTM1ZDg0NHl2TzJQaFBOUDErL2xYd1lCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
